name: .NET

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    name: Build and Test
    env:
      PROJECT_NAME: Starter.API
      CLOUDFLARE_PROJECT_NAME: netcore-webapi-starter-livingdoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get short commit hash
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        id: restore
        run: dotnet restore
      - name: Build
        id: build
        run: dotnet build --no-restore --configuration Release
      - name: Test
        id: test
        run: dotnet test --no-build --verbosity normal --configuration Release --logger "trx;LogFileName=test-results.trx"
      - name: Generate LivingDoc
        id: gen-livingdoc
        if: (success() || failure()) && steps.build.outcome == 'success'
        run: dotnet livingdoc feature-folder ${{ env.PROJECT_NAME }}.Tests/ -t ${{ env.PROJECT_NAME }}.Tests/bin/Release/net6.0/TestExecution.json
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        if: (success() || failure()) && steps.build.outcome == 'success'
        with:
          name: ${{ env.PROJECT_NAME }}-Release-${{ runner.os }}-${{ steps.vars.outputs.sha_short }}
          path: ${{ env.PROJECT_NAME }}/bin/Release/net6.0/**
      - name: Upload test results artifact
        uses: actions/upload-artifact@v3
        if: (success() || failure()) && steps.build.outcome == 'success'
        with:
          name: ${{ env.PROJECT_NAME }}.Tests-${{ runner.os }}-${{ steps.vars.outputs.sha_short }}
          path: ${{ env.PROJECT_NAME }}.Tests/TestResults/test-results.trx
      - name: Upload LivingDoc artifact
        if: (success() || failure()) && steps.gen-livingdoc.outcome == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PROJECT_NAME }}.Tests-LivingDoc-${{ runner.os }}-${{ steps.vars.outputs.sha_short }}
          path: LivingDoc.html
